version: "3.8"
services:
    # maildev:
    #     image: maildev/maildev
    #     container_name: maildev
    #     command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    #     ports:
    #       - "8081:80"
    #     restart: always
    #     networks:
    #       - dev
  ###> symfony/mailer ###
    # mailer:
    #   image: schickling/mailcatcher
    #   ports: ["1025", "1080"]
  ###< symfony/mailer ###
    php:
        build: 
          context: ./php
        container_name: php
        ports:
          - "8000:80"
        volumes:
          - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
          - ./app:/var/www
        restart: always
        networks:
          - dev
networks:
  dev:

